imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        openmindparser_mail:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/Mail.png"
            output: "bundles/openMindParser/img/back.png" 
        openmindparser_attach:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/attach.png"
            output: "bundles/openMindParser/img/back.png" 
        openmindparser_back:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/back.png"
            output: "bundles/openMindParser/img/back.png" 
        openmindparser_bell:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/bell.png"
            output: "bundles/openMindParser/img/bell.png" 
        openmindparser_bookmark:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/bookmark.png"
            output: "bundles/openMindParser/img/bookmark.png" 
        openmindparser_button_cancel:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/button_cancel.png"
            output: "bundles/openMindParser/img/button_cancel.png" 
        openmindparser_button_ok:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/button_ok.png"
            output: "bundles/openMindParser/img/button_ok.png" 
        openmindparser_clanbomber:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/clanbomber.png"
            output: "bundles/openMindParser/img/clanbomber.png" 
        openmindparser_clock:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/clock.png"
            output: "bundles/openMindParser/img/clock.png" 
        openmindparser_decrypted:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/decrypted.png"
            output: "bundles/openMindParser/img/decrypted.png" 
        openmindparser_desktop_new:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/desktop_new.png"
            output: "bundles/openMindParser/img/desktop_new.png" 
        openmindparser_encrypted:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/encrypted.png"
            output: "bundles/openMindParser/img/encrypted.png" 
        openmindparser_flag:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/flag.png"
            output: "bundles/openMindParser/img/flag.png" 
        openmindparser_forward:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/forward.png"
            output: "bundles/openMindParser/img/forward.png" 
        openmindparser_full_1:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-1.png"
            output: "/bundles/openMindParser/img/full-1.png"
        openmindparser_full_2:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-2.png"
            output: "bundles/openMindParser/img/full-2.png" 
        openmindparser_full_3:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-3.png"
            output: "bundles/openMindParser/img/full-3.png" 
        openmindparser_full_4:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-4.png"
            output: "bundles/openMindParser/img/full-4.png" 
        openmindparser_full_5:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-5.png"
            output: "bundles/openMindParser/img/full-5.png" 
        openmindparser_full_6:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-6.png"
            output: "bundles/openMindParser/img/full-6.png" 
        openmindparser_full_7:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/full-7.png"
            output: "bundles/openMindParser/img/full-7.png" 
        openmindparser_full_gohome:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/gohome.png"
            output: "bundles/openMindParser/img/gohome.png" 
        openmindparser_help:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/help.png"
            output: "bundles/openMindParser/img/help.png" 
        openmindparser_idea:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/idea.png"
            output: "bundles/openMindParser/img/idea.png" 
        openmindparser_kaddressbook:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/kaddressbook.png"
            output: "bundles/openMindParser/img/kaddressbook.png" 
        openmindparser_knotify:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/knotify.png"
            output: "bundles/openMindParser/img/knotify.png" 
        openmindparser_korn:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/korn.png"
            output: "bundles/openMindParser/img/korn.png" 
        openmindparser_ksmiletris:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/ksmiletris.png"
            output: "bundles/openMindParser/img/ksmiletris.png" 
        openmindparser_licq:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/licq.png"
            output: "bundles/openMindParser/img/licq.png" 
        openmindparser_messagebox_warning:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/messagebox_warning.png"
            output: "bundles/openMindParser/img/messagebox_warning.png" 
        openmindparser_password:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/password.png"
            output: "bundles/openMindParser/img/password.png" 
        openmindparser_pencil:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/pencil.png"
            output: "bundles/openMindParser/img/pencil.png" 
        openmindparser_penguin:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/penguin.png"
            output: "bundles/openMindParser/img/penguin.png" 
        openmindparser_stop:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/stop.png"
            output: "bundles/openMindParser/img/stop.png" 
        openmindparser_wizard:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/wizard.png"
            output: "bundles/openMindParser/img/wizard.png" 
        openmindparser_xmag:
            input: "%kernel.root_dir%/../vendor/arlisaha/open-mind-parser/img/xmag.png"
            output: "bundles/openMindParser/img/xmag.png"

#OpenMindReader Configuration    
app:
    file:
        folder_path: "/media/disque_storex/Divers/open_mind/"
    assets:
        output: "/bundles/openMindParser/img/"