FileController:
    resource: "@AppBundle/Resources/config/routing/file.yml"
    prefix: /
    
VisualizerController:
    resource: "@AppBundle/Resources/config/routing/visualizer.yml"
    prefix: /visualizer
