visualizer_html:
    path:      /html/{fileName}
    defaults:  { _controller: AppBundle:Visualizer:html }
    
visualizer_svg:
    path:      /svg/{fileName}
    defaults:  { _controller: AppBundle:Visualizer:svg }