services:
    app.parser:
        class: OpenMindParser\Parser
        
    app.converter.html:
        class: OpenMindParser\Converters\HTML\GenericHTMLConverter
        
    app.converter.json:
        class: OpenMindParser\Converters\JSON\GenericJSONConverter