services:
    open_mind_reader.parser:
        class: OpenMindParser\Parser
        
    open_mind_reader.converter.html:
        class: OpenMindParser\Converters\HTML\GenericHTMLConverter
        
    open_mind_reader.converter.json:
        class: OpenMindParser\Converters\JSON\GenericJSONConverter
        